POST http://localhost:3000/companies
Content-Type: application/json

{
  "name": "Freios Supremos"
}

#6488fef0226989c4f423de48

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "José Chociai",
  "email": "joselucaschociai@gmail.com",
  "password": "123",
  "companyId": "6488fef0226989c4f423de48"
}

<> 2023-06-13T003836.400.json
<> 2023-06-13T003655.500.json
<> 2023-06-13T003601.201.json
<> 2023-06-13T003525.400.json
<> 2023-06-13T003339.500.json
<> 2023-06-13T003147.500.json

###
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "joselucaschociai@gmail.com",
  "password": "123"
}

<> 2023-06-13T004022.201.json

###

GET http://localhost:3000/companies
Content-Type: application/json

<> 2023-06-13T131659.404.json
<> 2023-06-13T002859.200.json


###

POST http://localhost:3000/units
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg4ZmY4NWZmNWJkZjZhNTg1ZGI1ZGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ4OGZlZjAyMjY5ODljNGY0MjNkZTQ4IiwiaWF0IjoxNjg2NzAwMTUyfQ.ygKrK6tTM-d1KPlcajvYAsdJEIuT3dbitJtXtf5t3oo

{
  "name": "Unidade 1"
}


###


POST http://localhost:3000/assets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg4ZmY4NWZmNWJkZjZhNTg1ZGI1ZGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ4OGZlZjAyMjY5ODljNGY0MjNkZTQ4IiwiaWF0IjoxNjg2NzAwMTUyfQ.ygKrK6tTM-d1KPlcajvYAsdJEIuT3dbitJtXtf5t3oo


{
  "name": "Máquina de fazer freio",
  "description": "Faz freios",
  "model": "1234213",
  "ownerId": "6488f5f6f1e0534515f38ff2",
  "unitId": "64890082b1c71d51c724f805"
}
