GET http://localhost:8080/assets?sort={ "createdAt": -1 }
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDhmNmExNDlmYjAwMDk0YTM0NWZiYmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MDY2N2I0ZjFkODg0ZGU4NTAyM2JlIiwiaWF0IjoxNjg3MjA1Mjk4fQ.F-oiZggpc-1O-NaCW8Uit8_oMcB5T7U-0sHLSRkPSFA

###
GET http://localhost:8080/assets/648f9522f2e562c6f6ad23dc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDhmNmExNDlmYjAwMDk0YTM0NWZiYmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MDY2N2I0ZjFkODg0ZGU4NTAyM2JlIiwiaWF0IjoxNjg3MjA1Mjk4fQ.F-oiZggpc-1O-NaCW8Uit8_oMcB5T7U-0sHLSRkPSFA



###


POST http://localhost:8080/assets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDhmNmExNDlmYjAwMDk0YTM0NWZiYmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MDY2N2I0ZjFkODg0ZGU4NTAyM2JlIiwiaWF0IjoxNjg3MjA1Mjk4fQ.F-oiZggpc-1O-NaCW8Uit8_oMcB5T7U-0sHLSRkPSFA


{
  "name": "Máquina de fazer freio",
  "description": "Faz freios",
  "model": "1234213",
  "unitId": "648f8992ffc1119a58111aa4",
  "health": 0.5
}

###

PATCH http://localhost:8080/assets/648f9522f2e562c6f6ad23dc/healthLevel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDhmNmExNDlmYjAwMDk0YTM0NWZiYmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MDY2N2I0ZjFkODg0ZGU4NTAyM2JlIiwiaWF0IjoxNjg3MjA1Mjk4fQ.F-oiZggpc-1O-NaCW8Uit8_oMcB5T7U-0sHLSRkPSFA

{
  "healthLevel": 0.2312321231
}
