GET http://localhost:8080/assets?sort={ "createdAt": -1,  "unit.name": 1 }&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4

###
GET http://localhost:8080/assets/64925352281771ce53d5233c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4


###


POST http://localhost:8080/assets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4


{
  "name": "Máquina de fazer freio",
  "description": "Faz freios",
  "model": "1234213",
  "unitId": "649252ca2ba11f0e1f20f782",
  "health": 0.5
}

###

PATCH http://localhost:8080/assets/64925336281771ce53d5231e/healthLevel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4

{
  "healthLevel": 0.96
}
