GET http://localhost:8080/companies
Content-Type: application/json

###

POST http://localhost:8080/companies
Content-Type: application/json

{
  "name": "Freios Rivais",
  "cnpj": "86886567000122"
}

###

POST http://localhost:8080/companies
Content-Type: application/json

{
  "name": "Freios Rivais",
  "cnpj": "70538812000170"
}

###

PATCH http://localhost:8080/companies/6490cb22a636f24711907681
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkwY2IzMzczODc2OGIxNzZlOTg0YTkiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MGNiMjJhNjM2ZjI0NzExOTA3NjgxIiwiaWF0IjoxNjg3MjEzMDEwfQ.Xl96S22mD_etxsow2lSsZaT6XS5mume0pM1MlIbhZr4

{
  "name": "Freios Rivais"
}
