GET http://localhost:8080/units?sort={ "createdAt":  1 }
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkxMTBjMTliNzJkMjk0ZGNlM2Y0NmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MTEyYTg5YjcyZDI5NGRjZTNmNDZmIiwiaWF0IjoxNjg3MjI5MTY0fQ._pFdERR0U5sNxBtx2JMr7DTjAihum_onhn6lDU6NBOI


###

GET http://localhost:8080/units/648f9522f2e562c6f6ad23dc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkxMTBjMTliNzJkMjk0ZGNlM2Y0NmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MTEyYTg5YjcyZDI5NGRjZTNmNDZmIiwiaWF0IjoxNjg3MjI5MTY0fQ._pFdERR0U5sNxBtx2JMr7DTjAihum_onhn6lDU6NBOI


###

POST http://localhost:8080/units
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkxMTBjMTliNzJkMjk0ZGNlM2Y0NmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MTEyYTg5YjcyZDI5NGRjZTNmNDZmIiwiaWF0IjoxNjg3MjI5MTY0fQ._pFdERR0U5sNxBtx2JMr7DTjAihum_onhn6lDU6NBOI

{
  "name": "Unidade Teste replace"
}


###

PATCH http://localhost:8080/units/649112fad420bad7479e5170
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkxMTBjMTliNzJkMjk0ZGNlM2Y0NmEiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MTEyYTg5YjcyZDI5NGRjZTNmNDZmIiwiaWF0IjoxNjg3MjI5MTY0fQ._pFdERR0U5sNxBtx2JMr7DTjAihum_onhn6lDU6NBOI

{
  "name": "Unidade Teste 13"
}
