GET http://localhost:8080/units?sort={ "createdAt":  1 }
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4


###

GET http://localhost:8080/units/648f9522f2e562c6f6ad23dc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4


###

POST http://localhost:8080/units
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzEwOTg0fQ.kb1bUOLRNLL0nC5xWfKq5eeJV3fvvQlVSAAJevOcV10

{
  "name": "Unidade de Teste 2"
}


###

PATCH http://localhost:8080/units/649112fad420bad7479e5170
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkyNTIyMjhkZWM1MWNjZWJmYjRhMGQiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MjUyMWJmZjcwNmMwNTVjNWJhYmNmIiwiaWF0IjoxNjg3MzExMDY1fQ.qqpBMzacERH0fzKV-fBwi_UGy38oUK9cZ4FL7UDhup4

{
  "name": "Unidade Teste 13"
}
