GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDkwY2IzMzczODc2OGIxNzZlOTg0YTkiLCJ1c2VybmFtZSI6Impvc2VsdWNhc2Nob2NpYWlAZ21haWwuY29tIiwiY29tcGFueUlkIjoiNjQ5MGQzZGQxMjJjMzdmMmRmYmIzNDM2IiwiaWF0IjoxNjg3MjEzNTQwfQ.0qJyX21lMcsjBrPnz9-6RcLmVY2N27Id6yGgfHxj7DY

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "José Chociai",
  "cpf": "58371614063",
  "email": "joselucaschociai@gmail.com",
  "password": "123",
  "companyId": "6492521bff706c055c5babcf"
}

<> 2023-06-13T003836.400.json
<> 2023-06-13T003655.500.json
<> 2023-06-13T003601.201.json
<> 2023-06-13T003525.400.json
<> 2023-06-13T003339.500.json
<> 2023-06-13T003147.500.json

###
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "joselucaschociai@gmail.com",
  "password": "123"
}

<> 2023-06-13T004022.201.json

###
PATCH http://localhost:3000/users/648a576424ec7d428db07a17
Content-Type: application/json

{
  "companyId": ""
}
